const BASE_URL = "https://dips.sja.org.uk/NER/DutySystem-List.asp";
const RESOURCE_NAMES = ["CDT", "FA", "CFA", "AFA", "ER", "CREW", "HCP", "FATC", "AMB"];

function openListing(filter) {
	chrome.tabs.create({
		url: `${BASE_URL}?filter=${filter}`
	});
}

function setStatus(message) {
	document.getElementById("status").textContent = message;
}

function getFilterLabel(urlString) {
	try {
		const url = new URL(urlString);
		const filter = url.searchParams.get("filter");
		switch (filter) {
			case "mydist":
				return "County listing";
			case "myarea":
				return "Network listing";
			case "none":
				return "Region listing";
			default:
				return "DIPS listing";
		}
	} catch {
		return "DIPS listing";
	}
}

function getSheetConfig(urlString) {
	try {
		const url = new URL(urlString);
		const filter = url.searchParams.get("filter");

		switch (filter) {
			case "mydist":
				return {
					label: "County listing",
					page: "poster-county.html",
					title: "County Event Update",
					subtitle: "All events in the county that need staffing for the next 2 weeks are listed below. Please contact your Cadet Group Lead or Isaac Critchley to be booked on. Look to staff local events first.",
					bookingNotes: "Please contact your Cadet Group Lead or Isaac Critchley to be booked on. Look to staff local events first.",
					footerLeft: "Produced for Bradford Community Network Youth",
					footerRight: "by Isaac Critchley (isaac.critchley@sja.org.uk)"
				};
			case "myarea":
				return {
					label: "Network listing",
					page: "poster-network.html",
					title: "Network Event Update",
					subtitle: "All events across the network that need staffing for the next 2 weeks are listed below. Prioritise nearby cover first, then support wider network demand where you can.",
					bookingNotes: "Coordinate through your local lead first, then support wider network demand where cover is still outstanding.",
					footerLeft: "Produced for Bradford Community Network Youth",
					footerRight: "Network staffing view from DIPS"
				};
			case "none":
				return {
					label: "Region listing",
					page: "poster-region.html",
					title: "Region Event Update",
					subtitle: "All events across the region that need staffing for the next 2 weeks are listed below. Use this view to spot wider gaps and support larger requirements.",
					bookingNotes: "Use the regional sheet to spot larger staffing gaps, then coordinate bookings through the usual lead contacts.",
					footerLeft: "Produced for South & West Yorkshire",
					footerRight: "Regional staffing view from DIPS"
				};
			default:
				return {
					label: "DIPS listing",
					page: "poster-county.html",
					title: "Event Update",
					subtitle: "Events that need staffing for the next 2 weeks are listed below.",
					bookingNotes: "Coordinate bookings through the usual lead contacts.",
					footerLeft: "Produced from DIPS data",
					footerRight: "Generated by the scraper"
				};
		}
	} catch {
		return {
			label: "DIPS listing",
			page: "poster-county.html",
			title: "Event Update",
			subtitle: "Events that need staffing for the next 2 weeks are listed below.",
			bookingNotes: "Coordinate bookings through the usual lead contacts.",
			footerLeft: "Produced from DIPS data",
			footerRight: "Generated by the scraper"
		};
	}
}

function getWindowLabel(events) {
	const validDates = events
		.map(event => parseDate(event.date))
		.filter(Boolean)
		.sort((a, b) => a - b);

	if (!validDates.length) {
		return "Current scrape";
	}

	const first = formatDate(validDates[0]);
	const last = formatDate(validDates[validDates.length - 1]);
	return first === last ? first : `${first} to ${last}`;
}

function parseDate(value) {
	if (!value) return null;

	const direct = new Date(value);
	if (!Number.isNaN(direct.getTime())) return direct;

	const parts = String(value).match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);
	if (!parts) return null;

	const year = Number(parts[3].length === 2 ? `20${parts[3]}` : parts[3]);
	const parsed = new Date(year, Number(parts[2]) - 1, Number(parts[1]));
	return Number.isNaN(parsed.getTime()) ? null : parsed;
}

function formatDate(date) {
	return new Intl.DateTimeFormat("en-GB", {
		day: "2-digit",
		month: "short",
		year: "numeric"
	}).format(date);
}

async function getCurrentTab() {
	const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
	return tab;
}

async function scrapeCurrentListing() {
	const tab = await getCurrentTab();

	if (!tab?.url?.startsWith(BASE_URL)) {
		throw new Error("You must be on the DIPS DutySystem page to scrape.");
	}

	setStatus("Scraping current listing...");

	return new Promise((resolve, reject) => {
		chrome.tabs.sendMessage(tab.id, { action: "scrape" }, response => {
			if (chrome.runtime.lastError) {
				reject(new Error("Scraper not available on this page."));
				return;
			}

			if (!response) {
				reject(new Error("No response from scraper."));
				return;
			}

			if (!response.success) {
				reject(new Error(response.error || "Scrape failed."));
				return;
			}

			resolve({
				tab,
				events: response.data
			});
		});
	});
}

async function copyScrapeJson() {
	try {
		setStatus("Checking page...");
		const { events } = await scrapeCurrentListing();
		const json = JSON.stringify(events, null, 2);

		try {
			await navigator.clipboard.writeText(json);
			setStatus(`Done\n${events.length} events copied to clipboard`);
		} catch {
			setStatus(`Done\n${events.length} events ready (clipboard blocked)`);
		}
	} catch (error) {
		setStatus(`Error: ${error.message}`);
	}
}

async function openFilledSheet() {
	try {
		setStatus("Checking page...");
		const { tab, events } = await scrapeCurrentListing();
		const filterLabel = getFilterLabel(tab.url);
		const sheetConfig = getSheetConfig(tab.url);
		const payloadKey = `poster-${Date.now()}`;
		const payload = {
			title: `${sheetConfig.title}`,
			brand: "South & West Yorkshire",
			subtitle: sheetConfig.subtitle,
			bookingNotes: sheetConfig.bookingNotes,
			sourceLabel: `${filterLabel} via DIPS`,
			releaseDate: new Date().toLocaleString("en-GB"),
			windowLabel: getWindowLabel(events),
			footerLeft: sheetConfig.footerLeft,
			footerRight: sheetConfig.footerRight,
			resourceNames: RESOURCE_NAMES,
			events
		};

		await chrome.storage.local.set({ [payloadKey]: payload });
		const posterUrl = `${chrome.runtime.getURL(sheetConfig.page)}#key=${encodeURIComponent(payloadKey)}`;
		await chrome.tabs.create({ url: posterUrl });
		setStatus(`Filled sheet opened\n${events.length} events included`);
	} catch (error) {
		setStatus(`Error: ${error.message}`);
	}
}

document.getElementById("openRegional").onclick = () => openListing("none");
document.getElementById("openCounty").onclick = () => openListing("mydist");
document.getElementById("openNetwork").onclick = () => openListing("myarea");
document.getElementById("scrapeBtn").addEventListener("click", copyScrapeJson);
document.getElementById("posterBtn").addEventListener("click", openFilledSheet);
